[current]
"education" = ["phd", "mphil_mlfocus", "beng_mlfocus"]
"work" = ["arminternships", "gapyear"]
# "projects" = ["cambs_mphil", "warwick_typ", "warwick_hpes", "yk_gmd_io"]
"projects" = ["yk_gmd_io"]
publications = []

[current_projectheavy]
"education" = ["allcambs", "beng_minimal"]
"work" = ["arminternships", "gapyear"]
"projects" = ["cambs_mphil", "warwick_typ", "warwick_hpes", "yk_gmd_io"]
publications = []

[arm2021]
"education" = ["mphil", "beng_minimal", "alevels"]
"work" = ["arm2019", "gapyear"]
"projects" = [
    "warwick_typ",
    "warwick_aca",
    "warwick_dsd",
    # "turnip_gba",
    "turnip_dxd",
    "yk_gmd_io",
    # "toothwatch",
    # "warwick_browser",
    # "get_to_the_top",
    # "overgrowth"
]
publications = []

# https://www.kojimaproductions.jp/en/3D-rendering-programmer-effects-programmer
# https://web.archive.org/web/20251006224343/https://www.kojimaproductions.jp/en/3D-rendering-programmer-effects-programmer
# REQUIREMENTS
# - Experience with 1 or more successful game development
# - Thorough knowledge of mathematics
# - Capable of creating a system that can effectively use multi-core
# - Have an interest in game engine design and creation for next generation hardware
# *New graduates are not required to meet the above qualification(s)
# *If you are new to the industry, you do not have to meet all of the qualification(s), but please show us other qualities and/or abilities you may have instead.
# PREFERRED QUALIFICATIONS
# - Experience creating a game engine
# - Thorough knowledge of or experience using foreign game engines
# - English proficiency (enough to read a thesis report written in English)
# REQUIRED DOCUMENTS
# - Japanese CV (Rirekisho with photo) ※if available
#       # https://livinginjapan.net/2021/08/00631/
#   - Date
#   - Full Name
#   - DOB
#   - Gender
#   - Current address
#   - Contact info
#       - Cell phone number
#       - Email
#   - Academic + Work history https://livinginjapan.net/2021/08/00636/
#       - Order by date ascending, include high school
#       - work should include reason for leaving
#       - use official names for company and schools
#       - clearly mark internships
#       - "In the case of graduation school, enter “修了 (Completed)” rather than “卒業 (Graduated)”."
# - CV with the following information:
#   - Please specify all game titles you have been involved with in the past and the details of your duties while working on them. 
#   - Please specify any program languages that you can use, the number of years you have used them, and the typical contents you have produced with them. 
#   - Please specify software that you can use (Photoshop, Maya, Eclipse, etc.), the number of years you have used them, and the typical contents you have produced with them. 
#   - Please list two recent technical presentations and related articles that you found to be wonderful from a technical and expressive standpoint, and briefly explain the reason why. 
#   - Please name one game you recently played that you were interested in from a technical standpoint, and briefly explain the reason why.
# Projects/Work Samples
# New graduates and those who are new to the industry must turn in sample work. Anyone else who would like to share their work may also send in samples.
#   - Please include the following:
#   - An original programming work (will accept team projects). No restriction on type or number of work(s). Please send us anything that you feel would showcase your abilities
#   - An execution file of the build
#   - Video capture of the screen (because there is a chance the video won’t operate depending on the environment)
#   - A “readme.txt” file with necessary instructions for the submitted works. Please also explain the following in the readme.txt file.
#   - Execution method including the execution environment
#   - What your biggest challenge was in creating the work
#   - What area you especially put effort into and would like us to focus on
#   - If there were any source files you used for reference, what areas did you pull for reference? Please note the file name(s) for those area(s).
# Notes
# - If you used a library, functions, etc. that were created by other people, please separate those parts into a different file and list those file names.
# - This also applies to the following scenarios:
#   - If you used a function created by someone else
#   - If you referenced more than half of a source file
#   - If you used a free library (please specify the library name)
#   - If you used a library created by someone else (please specify the library name)
# - Please exclude confidential sources and information before submitting.
# - Since our system is unable to recognize an overseas post code, applicants from outside Japan do not have to enter a post code that matches their actual address. However, please ensure that all other address information are valid.
#
#
# A4 size (this is a CV i.e. shokumu keirekisho)
# https://livinginjapan.net/2021/08/00633/
# photograph should be 3x4cm https://livinginjapan.net/2021/08/00635/
[kojipro]
"education" = [
    "alevels_kojipro",
    "beng_kojipro",
    "mphil_kojipro",
    "phd_kojipro",
]
work = [
    "virtualarts_kojipro",
    "arminternships_kojipro",
]
projects = [
    "get_to_the_top_age",
    "virtualarts_univrs",
    "virtualarts_lightstream",
    "warwick_typ_kojipro",
    "yk_gmd_io_kojipro",
    # "turnip_dxd", # ?
    # "warwich_aca",
]
publications = [
    "mphil_thesis_rise",
    "cxl_article",
]
kojipro_presentations = [
    "nanite",
    "hypehype",
]
kojipro_game = [
    "alanwake2"
]
special = "kojipro"
jp_date = true
basics = { name = "Samuel Winslow Stark", location = { formatAddress = "REDACTED REDACTED REDACTED REDACTED REDACTED" } }
# , picture="profile_smol.jpg"
# decided against profile pic because it's just too big.
# TODO in special article, mention culling via AC Unity is also something I did?


[jump]
"education" = ["phd", "mphil_mlfocus", "beng_jump"]
"work" = ["arminternships_jump", "gapyear"]
"projects" = ["warwick_typ_jump"]
publications = []
basics = { name = "Samuel W. Stark", location = { formatAddress = "REDACTED REDACTED" }, phone = "+XX XXXX XXXXXX" }

[hw]
# ## NVIDIA 
# What we need to see:
#     Completing a Master's degree (or equivalent experience) in Electrical or Computer Engineering, or a Bachelor's degree with 6+ months of relevant experience.
#     Strong academic background in digital design and computer architecture.
#     Programming experience in Python or other scripting languages.
#     Knowledge of RTL design (Verilog) and digital design concepts.
#     Understanding of basic SOC architecture concepts.
#     Excellent problem-solving and analytical skills.
#     Proven teamwork and communication across multiple teams.

# ## APPLE
# Minimum Qualifications
#     Previous complex IP design experience required..
#     Understanding of implementing modern design techniques.
#     Hands on experience with energy-efficient and low-power logic design.
#     Strong background in computer architecture including one or more of: high-speed CMOS processor and controller blocks, cache controllers, bus-interface subsystems, integer and floating-point numeric units, digital filters, graphics processors, crossbar fabrics and other high-speed data-path control units.
#     Well-versed in logic optimisation, synthesis, timing analysis.
#     Fluency with RTL Verilog/VHDL syntax & hardware modelling.
#     Familiarity with logic simulation and debug environments as well as formal verification.
#     Ability to work well in a team and be productive under tight schedules.
#     Excellent communications skills, self-motivated and well-organised
"education" = ["phd_hw", "mphil_hw", "beng_hw"]
"work" = ["arminternships_hw", "gapyear"]
"projects" = ["warwick_typ_jump"]
publications = []
basics = { name = "Samuel W. Stark", location = { formatAddress = "REDACTED REDACTED" }, phone = "+XX XXXX XXXXXX" }

[gfx]
# "education" = [
#     "phd_kojipro",
#     "mphil_kojipro",
#     "beng_kojipro",
#     # "alevels_kojipro",
# ]
# work = [
#     "arminternships_kojipro",
#     "virtualarts_kojipro",
# ]
# projects = [
#     # "get_to_the_top",
#     "virtualarts_univrs",
#     "virtualarts_lightstream",
#     "warwick_typ_kojipro",
#     # "yk_gmd_io_kojipro",
#     # "turnip_dxd", # ?
#     # "warwich_aca",
# ]
publications = [
    "cxl_article",
    "mphil_thesis_rise",
]
basics = { name = "Samuel Winslow Stark", location = { formatAddress = "REDACTED REDACTED REDACTED REDACTED REDACTED" } }
"education" = ["phd_gfx", "mphil_gfx", "beng_gfx"]
"work" = [
    "arminternships_gfx",
    "virtualarts_gfx",
]
projects = [
    "get_to_the_top",
    "virtualarts_univrs",
    "virtualarts_lightstream",
    "warwick_typ_kojipro",
    "yk_gmd_io_kojipro",
]
special = "gfx"